objects/Broker__c.object
<CustomObject>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Contact_phone__c</fullName>
        <label>Contact phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>First_name__c</fullName>
        <label>First name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Customer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Immovables__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Immovables</relationshipLabel>
        <relationshipName>Immovables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_address__c</fullName>
        <formula>Town__c  + &quot;, &quot; +  Street_address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Initial cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_bathrooms__c</fullName>
        <label>Number of bathrooms</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_rooms__c</fullName>
        <label>Number of rooms</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Seller</label>
        <referenceTo>Seller__c</referenceTo>
        <relationshipLabel>Immovables</relationshipLabel>
        <relationshipName>Immovables</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>sales</fullName>
                </value>
                <value>
                    <fullName>the sale is temporarily suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_area__c</fullName>
        <label>Total area</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Immovables</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Immovables Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Immovables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Desired_price__c</fullName>
        <label>Desired price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Immovables__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Immovables</label>
        <referenceTo>Immovables__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_price__c</fullName>
        <label>Maximum price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Offer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Seller__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Seller</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Seller Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ImmovablesController.cls
public with sharing class ImmovablesController {
 	@AuraEnabled
    public static List<Immovables__c> getImmovables(String typeIm, String statusIm, Boolean sortArea, String searchText) {
        List<Immovables__c> imms;
        if(!String.isEmpty(searchText)){
            String s = 'SELECT Id, Name,Full_address__c, Total_area__c,  toLabel(Type__c), 	Initial_cost__c,Seller__r.Id,'+
                'Seller__r.Name, Seller__r.First_Name__c,  Seller__r.Last_Name__c, Seller__r.Contact_Phone__c, toLabel(Status__c)'+
                'FROM Immovables__c  WHERE Full_address__c Like \'%' + searchText + '%\' ORDER BY Status__c';
            imms = Database.query(s);
        }else{
        if(typeIm=='all'){
            if(sortArea){
                imms =  [SELECT Id, Name, 
                Full_address__c, 
                Total_area__c, 
                toLabel(Type__c), 	
                Initial_cost__c,
                Seller__r.Id,
                Seller__r.Name, 
                Seller__r.First_Name__c, 
                Seller__r.Last_Name__c,
                Seller__r.Contact_Phone__c,
                toLabel(Status__c)
                FROM Immovables__c 
                WHERE toLabel(Status__c) =:statusIm
                ORDER BY Total_area__c ASC];
            }else{
                imms =  [SELECT Id, Name, 
                    Full_address__c, 
                    Total_area__c, 
                    toLabel(Type__c), 	
                    Initial_cost__c,
                    Seller__r.Id,
                    Seller__r.Name, 
                    Seller__r.First_Name__c, 
                    Seller__r.Last_Name__c,
                    Seller__r.Contact_Phone__c,
                    toLabel(Status__c)
                    FROM Immovables__c 
                    WHERE toLabel(Status__c) =:statusIm
                    ORDER BY Total_area__c DESC];
            }   
        }else{
             if(sortArea){
                imms =  [SELECT Id, 
                    Name, 
                    Full_address__c, 
                    Total_area__c, 
                    toLabel(Type__c), 	
                    Initial_cost__c,
                    Seller__r.Id,
                    Seller__r.Name, 
                    Seller__r.First_Name__c, 
                    Seller__r.Last_Name__c,
                    Seller__r.Contact_Phone__c,
                    toLabel(Status__c)
                    FROM Immovables__c
                    WHERE Type__c=:typeIm AND toLabel(Status__c) =:statusIm
                    ORDER BY  Total_area__c ASC];
             }else{
                  imms =  [SELECT Id, 
                    Name, 
                    Full_address__c, 
                    Total_area__c, 
                    toLabel(Type__c), 	
                    Initial_cost__c,
                    Seller__r.Id,
                    Seller__r.Name, 
                    Seller__r.First_Name__c, 
                    Seller__r.Last_Name__c,
                    Seller__r.Contact_Phone__c,
                    toLabel(Status__c)
                    FROM Immovables__c
                    WHERE Type__c=:typeIm AND toLabel(Status__c) =:statusIm
                    ORDER BY  Total_area__c DESC];
             }
        }
        }
        
        return imms;
    }
    
    @AuraEnabled
    public static AggregateResult[]  getTypes() {
        // Perform isAccessible() checking first, then
        return [SELECT 
                toLabel(Type__c)	
                FROM Immovables__c
                GROUP BY Type__c
                ];
    }
    
     @AuraEnabled
    public static AggregateResult[]  getStatus(){
         return [SELECT 
                toLabel(Status__c)	
                FROM Immovables__c
                GROUP BY Status__c
                ];
    }
    
    
    
   public static Map<Id, String> recordtypemap {get;set;}
    
   @AuraEnabled        
    public static List<String> fetchRecordTypeValues(){
        List<Schema.RecordTypeInfo> recordtypes = Immovables__c.SObjectType.getDescribe().getRecordTypeInfos();    
        recordtypemap = new Map<Id, String>();
        for(RecordTypeInfo rt : recordtypes){
            if(rt.getName() != 'Master')
            recordtypemap.put(rt.getRecordTypeId(), rt.getName());
        }        
        System.debug(recordtypemap);
        return recordtypemap.values();
    }
    
    @AuraEnabled
    public static Id getRecTypeId(String recordTypeLabel){
        Id recid = Schema.SObjectType.Immovables__c.getRecordTypeInfosByName().get(recordTypeLabel).getRecordTypeId();        
        return recid;
    }  
    
    
    @AuraEnabled
    public static Integer deleteRecord(String recordId){
         AggregateResult[] countImms = [SELECT COUNT(Id) FROM Immovables__c WHERE Id = :recordId];
         AggregateResult[] countImmsAfter = new List<AggregateResult>();
        
        if(countImms.size() != 0){
            Immovables__c delRec  = new Immovables__c(Id=recordId);
          
            try {
                delete delRec;
                return countImms.size();
            } catch (DmlException e) {
                    return -1;
            }   
        }else 
            return -2;
        
    }
    
    @AuraEnabled
    public static List<Offer__c> getOffersByImm(String ImmovablesId){
        List<Offer__c> listOffer =  [
            SELECT Id, Name, Maximum_price__c, Desired_price__c,  
            Customer__r.Id,  Customer__r.First_name__c, Customer__r.Last_name__c, Customer__r.Contact_phone__c
            FROM Offer__c 
            WHERE Immovables__c=:ImmovablesId
        	ORDER BY Desired_price__c DESC];
        
        return listOffer;
    }
    
    @AuraEnabled
    public static List<Immovables__c> getSimilarImmovables (Id recordId, Integer rooms, Integer baths) {
             return [
                 SELECT Id, Name, Number_of_rooms__c,Number_of_bathrooms__c, Full_address__c,  toLabel(Status__c),  Initial_cost__c, Broker__r.Name, Broker__r.Id, toLabel(Type__c)
                 FROM Immovables__c 
                 WHERE Id != :recordId AND Number_of_rooms__c = :rooms AND Number_of_bathrooms__c = :baths 
                 ORDER BY Initial_cost__c
                 LIMIT 10
                 
             ];
        
     }
    
    @AuraEnabled
    public static List<Immovables__c> findAllWithLocation() {
    return [SELECT Id, Name, Full_address__c, Location__Latitude__s, Location__Longitude__s
            FROM Immovables__c
            WHERE Location__Latitude__s != NULL AND Location__Longitude__s != NULL
            LIMIT 10];
    }
}